/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Dialog: typeof import('primevue/dialog')['default']
    GetUris: typeof import('./src/components/GetUris.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
